drop table if exists t_install_order;

/*==============================================================*/
/* Table: S_CORP                                                */
/*==============================================================*/
create table t_install_order
(
   ORDER_ID              varchar(100) not null comment '本实体记录的唯一标识，产生规则为流水号',
   CORP_NO                varchar(32) comment '公司编号',
   ORDER_NO             varchar(32) comment '订单编码',
   ORDER_TIME      datetime comment '提报时间 yyyymmdd hhmmss',
   CHECK_NO             varchar(32) comment '巡检编码',
   INSTALL_CONTACT      varchar(32) comment '联系人',
   INSTALL_CONTACT_PHONE      varchar(32) comment '联系人电话',
   INSTALL_PROVINCE      varchar(32) comment '安装省份',
   INSTALL_CITY      varchar(32) comment '安装城市',
   INSTALL_REGION      varchar(32) comment '安装区域',
   INSTALL_ADDRESS      varchar(120) comment '安装地址',
   ORDER_REMARK         varchar(120) comment '订单备注',
   PILE_CODE         varchar(120) comment '充电桩编码',
   PILE_MODEL        varchar(64) comment '充电桩型号',
   PILE_MODEL_NAME     varchar(256) comment '充电桩型号名称',
   PILE_TYPE        varchar(8) comment '01 壁挂式 02 立柱式',
   PILE_TYPE_NAME     varchar(64) comment '01 壁挂式 02 立柱式',
   SUPPLIER_NO     varchar(32) comment '服务商编码',
   SUPPLIER_NAME     varchar(64) comment '服务商名称',
   DISPATCH_REMARK     varchar(256) comment '派单备注',
   RECEIVE_STATUS      varchar(8) DEFAULT  '01' comment '01 未签收 02 签收 03 拒绝',
   RECEIVE_STATUS_NAME     varchar(64) DEFAULT  '未签收' comment '01 未签收 02 签收 03 拒绝',
   RECEIVE_REMARK     varchar(256) comment '派单备注',
   CONTACT_CUST_TIME      datetime comment '联系客户时间 yyyymmdd hhmmss',
   APPOINTMENT_TIME      datetime comment '预约勘察时间 yyyymmdd hhmmss',
   APPOINTMENT_REMARK      varchar(256)  comment '预约备注',
   CHECK_USER_NO      varchar(32)  comment '勘察人员编码',
   CHECK_USER_NAME      varchar(256)  comment '勘察人员编码',
   CHECK_USER_PHONE      varchar(256)  comment '勘察人员电话',
   ASSIGN_CHECK_REMARK      varchar(256)  comment '派单勘察备注',
   CHECK_TIME      datetime comment '勘察时间 yyyymmdd hhmmss',
   CHECK_FINISH_TIME   datetime comment '勘察结束时间 yyyymmdd hhmmss',
   DISPATCH_TIME    datetime comment '派单时间 yyyymmdd hhmmss',
   WIRE_LENGTH      int comment '布线距离',
   INSTALL_FLG      varchar(8)  comment '是否报装 01 是 02 否',
   INSTALL_FLG_NAME     varchar(64)   comment '是否报装 01 是 02 否',
   ESTIMATE_PRICE     decimal(12,2) comment '预计价格',
   ELEC_TYPE      varchar(8) comment '用电类型 01 物业电 02 自家电 03 国网电',
   ELEC_TYPE_NAME     varchar(64) comment '用电类型 01 物业电 02 自家电 03 国网电',
   RECEIVE_TIME          datetime comment '签收时间 yyyymmdd hhmmss',
   INSTALL_METHOD_FILE     varchar(256) comment '安装方案',
   OTHER_FILE     varchar(256) comment '其他附件',
   CHECK_REMARK               varchar(256) comment '勘察备注',
   APPOINTMENT_INSTALL_TIME      datetime comment '预约安装时间 yyyymmdd hhmmss',
   INSTALL_CONTACT_CUST_TIME      datetime comment '联系客户时间 yyyymmdd hhmmss',
   APPOINTMENT_INSTALL_REMARK      varchar(256) comment '预约安装备注',
   INSTALL_USER_NO      varchar(32)  comment '安装人员编码',
   INSTALL_USER_NAME      varchar(256)  comment '安装人员名称',
   INSTALL_USER_PHONE      varchar(256)  comment '安装人员电话',
   ASSIGN_INSTALL_REMARK      varchar(256)  comment '派单勘察备注',
   INSTALL_TIME       datetime comment '安装开始时间 yyyymmdd hhmmss',
   INSTALL_FINISH_TIME       datetime comment '安装结束时间 yyyymmdd hhmmss',
   INSTALL_TYPE      varchar(8) comment '铺设方式 01 穿管 02 桥架 03 地沟 04 暗孵 05 其他',
   INSTALL_TYPE_NAME      varchar(64) comment '铺设方式 01 穿管 02 桥架 03 地沟 04 暗孵 05 其他',
   ACTUAL_PRICE     decimal(12,2) comment '收费金额',
   CONNECT_FLG      varchar(8) comment '是否联网 01 是 02 否',
   CONNECT_FLG_NAME     varchar(64) comment '是否联网 01 是 02 否',
   GPS_LON     varchar(64) comment 'GPS经度',
   GPS_LAT     varchar(64) comment 'GPS维度',
   SETTLE_REMARK               varchar(256) comment '结算备注',
   SETTLE_VERIFY_FLG              varchar(256) comment '结算申请标志',
   PERSON_PILE_PIC               varchar(256) comment '人桩合影',
   INSTALL_CONFIRM_FILE               varchar(256) comment '安装确认书',
   OTHER_INSTALL_FILE               varchar(256) comment '安装确认书',
   INSTALL_REMARK      varchar(256)  comment '安装备注',
   SUPPLIER_CONFIRM_TIME      datetime comment '服务商确认时间 yyyymmdd hhmmss',
   SUPPLIER_CONFIRM_FLG      varchar(8)  DEFAULT  '02' comment '是否确认 01 是 02 否',
   SUPPLIER_CONFIRM_FLG_NAME     varchar(64) DEFAULT '否'  comment '是否确认 01 是 02 否',

   VERIFY_FLG      varchar(8)  DEFAULT  '01' comment '车厂审核 01 未审核 02 审核通过 03 审核拒绝',
   VERIFY_FLG_NAME     varchar(64) DEFAULT '未审核'  comment '车厂审核 01 未审核 02 审核通过 03 审核拒绝',
   VERIFY_REMARK     varchar(256) comment '审核备注',
   VERIFY_TIME      datetime comment '审核时间 yyyymmdd hhmmss',
   CRM_ROLLBACK_REMARK   varchar(256) comment 'CRM退回备注',
   DISPATCH_CHECK_SUBMIT_TIME      datetime comment '派单勘察提交时间 yyyymmdd hhmmss',
   DISPATCH_INSTALL_SUBMIT_TIME      datetime comment '派单安装提交时间 yyyymmdd hhmmss',
   GRADE_SUBMIT_TIME      datetime comment '满意度提交时间 yyyymmdd hhmmss',

   BEGIN_CACLE      varchar(8)  default 'N' comment '是否开始做废动作 Y 是 N 否',

   SETTLE_FLG      varchar(8)  default 'N' comment '是否结算 Y 是 N 否',

   FINISH_FLG      varchar(8)  default 'N' comment '是否完成 Y 是 N 否',
   FINISH_TIME     datetime comment '安装完成时间',
   INSPECTION_TOUR_FLG      varchar(8)  default 'N' comment '是否巡检 Y 是 N 否',
   CRM_ROLLBACK_FLG     varchar(8)  default 'N' comment '是否CRM回退 Y 是 N 否',
   IS_DEL               varchar(8) comment '是否删除:Y删除 N有效',
   CREATED_BY_NAME      varchar(256) comment '创建者',
   CREATED_WHEN         datetime comment '创建时间',
   LAST_MODIFIED_BY_NAME varchar(256) comment '更新者',
   LAST_MODIFIED_WHEN   datetime comment '更新时间',
   primary key (ORDER_ID),
    KEY `IDX01_DEL_FLG` (`IS_DEL`),
  KEY `IDX01_ORDER_NO` (`ORDER_NO`) USING BTREE,
  KEY `IDX01_CORP_NO` (`CORP_NO`) USING BTREE,
  KEY `IDX01_SPL_NO` (`SUPPLIER_NO`) USING BTREE,
  KEY `IDX01_INSTALL_PROVINCE` (`INSTALL_PROVINCE`) USING BTREE,
  KEY `IDX01_INSTALL_CITY` (`INSTALL_CITY`) USING BTREE,
  KEY `IDX01_SETTLE_FLG` (`SETTLE_FLG`) USING BTREE,
  KEY `IDX01_FINISH_FLG` (`FINISH_FLG`) USING BTREE,
  KEY `IDX01_INSPECTION_TOUR_FLG` (`INSPECTION_TOUR_FLG`) USING BTREE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin
COMMENT = '安装订单表';
