drop table if exists t_delivery_order;

/*==============================================================*/
/* Table: S_CORP                                                */
/*==============================================================*/
create table t_delivery_order
(
   ORDER_ID              varchar(100) not null comment '本实体记录的唯一标识，产生规则为流水号',
   CORP_NO                varchar(32) comment '公司编号',
   ORDER_NO             varchar(32) comment '订单编码',
   ORDER_TIME      datetime comment '提报时间 yyyymmdd hhmmss',
   INSTALL_CONTACT      varchar(32) comment '联系人',
   INSTALL_CONTACT_PHONE      varchar(32) comment '联系人电话',
   INSTALL_PROVINCE      varchar(32) comment '安装省份',
   INSTALL_CITY      varchar(32) comment '安装城市',
   INSTALL_REGION      varchar(32) comment '安装区域',
   INSTALL_ADDRESS      varchar(120) comment '安装地址',
   PILE_TYPE      varchar(8) comment '01 壁挂式 02 立柱式',
   PILE_TYPE_NAME     varchar(64) comment '01 壁挂式 02 立柱式',
   PILE_CODE      varchar(120) comment '充电桩编码',
   SUPPLIER_NO     varchar(32) comment '服务商编码',
   SUPPLIER_NAME     varchar(64) comment '服务商名称',
   DISPATCH_REMARK     varchar(256) comment '派单备注',
   SETTLE_REMARK               varchar(256) comment '结算备注',
   SETTLE_VERIFY_FLG              varchar(256) comment '结算申请标志',
   DISPATCH_TIME    datetime comment '派单时间 yyyymmdd hhmmss',
   RECEIVE_STATUS      varchar(8) DEFAULT  '01' comment '01 未签收 02 签收 03 拒绝',
   RECEIVE_STATUS_NAME     varchar(64) DEFAULT  '未签收' comment '01 未签收 02 签收 03 拒绝',
   CUST_RECEIVE_TIME      datetime comment '客户签收时间 yyyymmdd hhmmss',
   RECEIVE_REMARK     varchar(256) comment '派单备注',
   RECEIVE_TIME          datetime comment '签收时间 yyyymmdd hhmmss',
   CONTACT_CUST_TIME      datetime comment '联系客户时间 yyyymmdd hhmmss',
   APPOINTMENT_TIME      datetime comment '预约时间 yyyymmdd hhmmss',
   DELIVERY_TIME      datetime comment '配送时间 yyyymmdd hhmmss',
   DELIVERY_FINISH_TIME    datetime comment '配送结束时间 yyyymmdd hhmmss',
   APPOINTMENT_REMARK      varchar(256)  comment '预约备注',
   DELIVERY_TYPE      varchar(8) comment '配送类型：01 物流 02 自送',
   DELIVERY_TYPE_NAME     varchar(64) comment '配送类型：01 物流 02 自送',
   DELIVERY_NAME     varchar(64) comment '物流公司',
   DELIVERY_NO     varchar(64) comment '物流单号',
   DELIVERY_REMARK     varchar(256) comment '物流单号',
   DELIVERY_FILE     varchar(256) comment '物流单号附件',
   ORDER_REMARK         varchar(120) comment '订单备注',
   SUPPLIER_CONFIRM_TIME      datetime comment '服务商确认时间 yyyymmdd hhmmss',
   PILE_MODEL        varchar(64) comment '充电桩型号',
   PILE_MODEL_NAME     varchar(256) comment '充电桩型号名称',
   SUPPLIER_CONFIRM_FLG      varchar(8)  DEFAULT  '02' comment '是否确认 01 是 02 否',
   SUPPLIER_CONFIRM_FLG_NAME     varchar(64) DEFAULT '否'  comment '是否确认 01 是 02 否',
   SETTLE_FLG      varchar(8)  default 'N' comment '是否结算 Y 是 N 否',
   FINISH_FLG      varchar(8)  default 'N' comment '是否完成 Y 是 N 否',
   FINISH_TIME     datetime comment '订单完成时间',
   BEGIN_CACLE      varchar(8)  default 'N' comment '是否开始做废动作 Y 是 N 否',
   VERIFY_FLG      varchar(8)  DEFAULT  '01' comment '车厂审核 01 未审核 02 审核通过 03 审核拒绝',
   VERIFY_FLG_NAME     varchar(64) DEFAULT '未审核'  comment '车厂审核 01 未审核 02 审核通过 03 审核拒绝',
   VERIFY_REMARK     varchar(256) comment '审核备注',
   VERIFY_TIME      datetime comment '审核时间 yyyymmdd hhmmss',
   CRM_ROLLBACK_FLG     varchar(8)  default 'N' comment '是否CRM回退 Y 是 N 否',
   CRM_ROLLBACK_REMARK   varchar(256) comment 'CRM退回备注',
   GRADE_SUBMIT_TIME      datetime comment '满意度提交时间 yyyymmdd hhmmss',
   IS_DEL               varchar(8) comment '是否删除:Y删除 N有效',
   CREATED_BY_NAME      varchar(256) comment '创建者',
   CREATED_WHEN         datetime comment '创建时间',
   LAST_MODIFIED_BY_NAME varchar(256) comment '更新者',
   LAST_MODIFIED_WHEN   datetime comment '更新时间',
   primary key (ORDER_ID),
  KEY `IDX07_CORP_NO` (`CORP_NO`) USING BTREE,
  KEY `IDX07_ORDER_NO` (`ORDER_NO`) USING BTREE,
  KEY `IDX07_INSTALL_CONTACT` (`INSTALL_CONTACT`) USING BTREE,
  KEY `IDX07_INSTALL_CONTACT_PHONE` (`INSTALL_CONTACT_PHONE`) USING BTREE,
  KEY `IDX07_INSTALL_PROVINCE` (`INSTALL_PROVINCE`) USING BTREE,
  KEY `IDX07_INSTALL_CITY` (`INSTALL_CITY`) USING BTREE,
  KEY `IDX07_INSTALL_ADDRESS` (`INSTALL_ADDRESS`) USING BTREE,
  KEY `IDX07_SUPPLIER_NO` (`SUPPLIER_NO`) USING BTREE,
  KEY `IDX07_SUPPLIER_NAME` (`SUPPLIER_NAME`) USING BTREE,
  KEY `IDX07_FINISH_FLG` (`FINISH_FLG`) USING BTREE,
  KEY `IDX07_IS_DEL` (`IS_DEL`) USING BTREE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin
COMMENT = '安装订单表';
