CREATE
	OR REPLACE VIEW v_dashboard_rank AS SELECT
	UUID() AS id,
	INSTALL_PROVINCE,
	CAR_VEHICLE,
	FINISH_FLG,
	SUPPLIER_NO,
	CORP_NO,
	SUM( ORDER_NUM ) AS ORDER_NUM
FROM
	(
	SELECT
		t1.INSTALL_PROVINCE,
		t2.CAR_VEHICLE,
		t1.FINISH_FLG,
		t1.CORP_NO,
		t1.SUPPLIER_NO,
		COUNT( 1 ) AS ORDER_NUM
	FROM
		t_install_order t1
		LEFT JOIN t_order_car t2 ON t1.ORDER_NO = t2.ORDER_NO and t2.IS_DEL='N'
	WHERE t1.IS_DEL='N'
		and t1.CRM_ROLLBACK_FLG='N'
		and t1.BEGIN_CACLE='N'
	GROUP BY
		t1.INSTALL_PROVINCE,
		t2.CAR_VEHICLE,
		t1.CORP_NO,
		t1.SUPPLIER_NO,
		t1.FINISH_FLG UNION ALL
	SELECT
		t1.INSTALL_PROVINCE,
		t2.CAR_VEHICLE,
		t1.FINISH_FLG,
		t1.CORP_NO,
		t1.SUPPLIER_NO,
		COUNT( 1 ) AS ORDER_NUM
	FROM
		t_delivery_order t1
		LEFT JOIN t_order_car t2 ON t1.ORDER_NO = t2.ORDER_NO and t2.IS_DEL='N'
	WHERE t1.IS_DEL='N'
		and t1.CRM_ROLLBACK_FLG='N'
		and t1.BEGIN_CACLE='N'
	GROUP BY
		t1.INSTALL_PROVINCE,
		t2.CAR_VEHICLE,
		t1.CORP_NO,
		t1.SUPPLIER_NO,
		t1.FINISH_FLG
	) T
GROUP BY
	INSTALL_PROVINCE,
	CAR_VEHICLE,
	FINISH_FLG,
	SUPPLIER_NO,
	CORP_NO;