CREATE
	OR REPLACE VIEW v_complain_order AS SELECT
	T1.COMPLAIN_ID AS COMPLAIN_ID,
	T1.CORP_NO AS CORP_NO,
	T1.COMPLAIN_NO AS COMPLAIN_NO,
	T1.ORDER_NO AS ORDER_NO,
	T1.CONTACT_CUST_TIME AS CONTACT_CUST_TIME,
	T1.SUPPLIER_NO AS SUPPLIER_NO,
	T1.SUPPLIER_NAME AS SUPPLIER_NAME,
	T1.COMPLAIN_DESC AS COMPLAIN_DESC,
	T1.COMPLAIN_DESC_NAME AS COMPLAIN_DESC_NAME,
	T1.COMPLAIN_REMARK AS COMPLAIN_REMARK,
	T1.COMPLAIN_TIME AS COMPLAIN_TIME,
	T1.RECEIVE_TIME AS RECEIVE_TIME,
	T1.SOLUTION_TIME AS SOLUTION_TIME,
	T1.RECEIVE_DESC AS RECEIVE_DESC,
	T1.SOLUTION_DESC AS SOLUTION_DESC,
	T1.SOLUTION_SUPPLIER_NO AS SOLUTION_SUPPLIER_NO,
	T1.SOLUTION_SUPPLIER_NAME AS SOLUTION_SUPPLIER_NAME,
	T1.SOLUTION_REMARK AS SOLUTION_REMARK,
	T1.CAR_OWNER AS CAR_OWNER,
	T1.CAR_OWNER_PHONE AS CAR_OWNER_PHONE,
	T1.VIN_NO AS VIN_NO,
	T1.SCRM_NO AS SCRM_NO,
	T1.FINISH_FLG AS FINISH_FLG,
	T1.RECEIVE_STATUS AS RECEIVE_STATUS,
	T1.RECEIVE_STATUS_NAME AS RECEIVE_STATUS_NAME,
	T1.SCRM_CONTENT_DESC AS SCRM_CONTENT_DESC,
	T1.IS_DEL AS IS_DEL,
	T1.CREATED_BY_NAME AS CREATED_BY_NAME,
	T1.CREATED_WHEN AS CREATED_WHEN,
	T1.LAST_MODIFIED_BY_NAME AS LAST_MODIFIED_BY_NAME,
	T1.LAST_MODIFIED_WHEN AS LAST_MODIFIED_WHEN,
	T2.FOLLOW_SEQ AS FOLLOW_SEQ,
	T2.STEP_NAME AS STEP_NAME,
	T2.POSITION_CODES AS POSITION_CODES,
	T3.DEALER_NAME AS DEALER_NAME,
	T3.DEALER_CONTACT AS DEALER_CONTACT,
	T3.DEALER_TEL AS DEALER_TEL,
	T3.SALE_DATE AS SALE_DATE,
	T3.CAR_VEHICLE AS CAR_VEHICLE,
	T3.ENGINE_NO AS ENGINE_NO,
	T1.FINISH_TIME AS FINISH_TIME,
	T2.STEP_MATRIX AS STEP_MATRIX,
  (CASE WHEN T4.CASE_STATUS ='Closed' then 'Y'
	else 'N' end
	)	as SCRM_FINISH_FLG
FROM
	t_complain_order T1
	LEFT JOIN t_order_step T2 ON T1.COMPLAIN_NO = T2.ORDER_NO
	AND T2.CURRENT_STEP_FLG = 'Y' AND T2.IS_DEL = 'N'
	LEFT JOIN t_order_car T3 ON T1.ORDER_NO = T3.ORDER_NO AND T3.IS_DEL = 'N'
	LEFT JOIN t_scrm_info T4 on T1.SCRM_NO=T4.SCRM_NO and T4.IS_DEL='N'
WHERE
	T1.IS_DEL = 'N'
