CREATE
	OR REPLACE VIEW v_order_cancel AS SELECT

	t1.STEP_ID,
	t1.CORP_NO,
	t1.POSITION_CODES,
	t1.STEP_NAME,
	t1.FOLLOW_SEQ,
	t1.STEP_MATRIX,
	t1.ORDER_NO,
	t1.RESULT_CODE,
	t1.STEP_TIME,
	t1.CREATED_WHEN,
	t1.CREATED_BY_NAME,
	t1.LAST_MODIFIED_WHEN,
	t1.LAST_MODIFIED_BY_NAME,
	t1.FOLLOW_CODE,
	t1.FOLLOW_NAME,
	t1.IS_DEL,
	t2.SUPPLIER_NO,
	t2.SUPPLIER_NAME,
	t2.ORDER_TIME,
	t2.INSTALL_CONTACT,
	t2.INSTALL_CONTACT_PHONE,
	t2.INSTALL_ADDRESS,
	t3.VIN_NO,
	t3.CAR_OWNER,
	t3.CAR_OWNER_PHONE,
	t3.DEALER_NAME,
	t4.ORDER_TYPE,
	t4.APPLY_NO,
	(case when (t1.LAST_STEP='Y' and  LENGTH(t1.STEP_TIME) >0  )
	then 'Y'
	else 'N'
	end
	)  as FINISH_FLG
FROM
	t_order_step t1,
	t_install_order t2,
	t_order_car t3,
	t_order_cancel t4
WHERE
	t4.APPLY_NO = t1.ORDER_NO
	AND t2.ORDER_NO = t3.ORDER_NO
	AND t2.ORDER_NO = t4.ORDER_NO
    AND t1.CURRENT_STEP_FLG = 'Y'
    AND T2.IS_DEL='N'
	AND T4.IS_DEL='N'
	AND T3.IS_DEL='N'
	AND T1.IS_DEL='N'
  UNION ALL
SELECT
	t1.STEP_ID,
	t1.CORP_NO,
	t1.POSITION_CODES,
	t1.STEP_NAME,
	t1.FOLLOW_SEQ,
	t1.STEP_MATRIX,
	t1.ORDER_NO,
	t1.RESULT_CODE,
	t1.STEP_TIME,
	t1.CREATED_WHEN,
	t1.CREATED_BY_NAME,
	t1.LAST_MODIFIED_WHEN,
	t1.LAST_MODIFIED_BY_NAME,
	t1.FOLLOW_CODE,
	t1.FOLLOW_NAME,
	t1.IS_DEL,
	t2.SUPPLIER_NO,
	t2.SUPPLIER_NAME,
	t2.ORDER_TIME,
	t2.INSTALL_CONTACT,
	t2.INSTALL_CONTACT_PHONE,
	t2.INSTALL_ADDRESS,
	t3.VIN_NO,
	t3.CAR_OWNER,
	t3.CAR_OWNER_PHONE,
	t3.DEALER_NAME,
	t4.ORDER_TYPE,
	t4.APPLY_NO,
	(case when (t1.LAST_STEP='Y' and  LENGTH(t1.STEP_TIME) >0  )
	then 'Y'
	else 'N'
	end
	)  as  FINISH_FLG
FROM
	t_order_step t1,
	t_delivery_order t2,
	t_order_car t3,
	t_order_cancel t4
WHERE
	t4.APPLY_NO = t1.ORDER_NO
	AND t2.ORDER_NO = t3.ORDER_NO
	AND t2.ORDER_NO = t4.ORDER_NO
    AND t1.CURRENT_STEP_FLG = 'Y'
    AND T2.IS_DEL='N'
	AND T4.IS_DEL='N'
	AND T3.IS_DEL='N'
	AND T1.IS_DEL='N'